---
- name: Filter already installed python versions
  shell: pyenv whence 2to3
  register: pyenv_installed_versions
  changed_when: false
  ignore_errors: true
  
- name: Install Python interpreters "{{ pyenv_python_versions }}"
  shell: pyenv install {{ item }}
  with_items: "{{ pyenv_python_versions | difference(pyenv_installed_versions.stdout_lines)}}"
  when: pyenv_installed_versions is defined
